<x-layout>
    <x-main-header/>
    <x-brands/>
    <x-service-features/>
    <x-slide-view/>
    <x-call/>
    <x-featured-products/>
    <x-newsletter/>
    <x-recent-products/>
    <x-review-cards/>
</x-layout>
